# Jekyll Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: OER Curriculum Map
tagline: open textbook alternatives for common courses
description: "Connecting OER textbooks to Idaho GEM courses to save students money and lower barriers to education." 
keywords: university of idaho, open educational resources, OER, open textbooks
email: ewilliamson@uidaho.edu

# url variables
url: https://uidaholib.github.io
baseurl: /oer-curriculum-map
